/**
 * レンタル予約システムの公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddReservationDto model module.
 * @module dto/AddReservationDto
 * @version 0.0.1-SNAPSHOT
 */
class AddReservationDto {
    /**
     * Constructs a new <code>AddReservationDto</code>.
     * 予約登録用DTO
     * @alias module:dto/AddReservationDto
     * @param endDateTime {String} 日時型
     * @param rentalItemId {Number} 
     * @param startDateTime {String} 日時型
     * @param userAccountId {Number} 
     */
    constructor(endDateTime, rentalItemId, startDateTime, userAccountId) { 
        
        AddReservationDto.initialize(this, endDateTime, rentalItemId, startDateTime, userAccountId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, endDateTime, rentalItemId, startDateTime, userAccountId) { 
        obj['endDateTime'] = endDateTime;
        obj['rentalItemId'] = rentalItemId;
        obj['startDateTime'] = startDateTime;
        obj['userAccountId'] = userAccountId;
    }

    /**
     * Constructs a <code>AddReservationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/AddReservationDto} obj Optional instance to populate.
     * @return {module:dto/AddReservationDto} The populated <code>AddReservationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddReservationDto();

            if (data.hasOwnProperty('endDateTime')) {
                obj['endDateTime'] = ApiClient.convertToType(data['endDateTime'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('rentalItemId')) {
                obj['rentalItemId'] = ApiClient.convertToType(data['rentalItemId'], 'Number');
            }
            if (data.hasOwnProperty('startDateTime')) {
                obj['startDateTime'] = ApiClient.convertToType(data['startDateTime'], 'String');
            }
            if (data.hasOwnProperty('userAccountId')) {
                obj['userAccountId'] = ApiClient.convertToType(data['userAccountId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * 日時型
 * @member {String} endDateTime
 */
AddReservationDto.prototype['endDateTime'] = undefined;

/**
 * @member {String} note
 */
AddReservationDto.prototype['note'] = undefined;

/**
 * @member {Number} rentalItemId
 */
AddReservationDto.prototype['rentalItemId'] = undefined;

/**
 * 日時型
 * @member {String} startDateTime
 */
AddReservationDto.prototype['startDateTime'] = undefined;

/**
 * @member {Number} userAccountId
 */
AddReservationDto.prototype['userAccountId'] = undefined;






export default AddReservationDto;

