/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddRentalItemEventDto model module.
 * @module dto/AddRentalItemEventDto
 * @version 2.0.0
 */
class AddRentalItemEventDto {
    /**
     * Constructs a new <code>AddRentalItemEventDto</code>.
     * レンタル品登録用DTO
     * @alias module:dto/AddRentalItemEventDto
     * @param serialNo {String} 
     */
    constructor(serialNo) { 
        
        AddRentalItemEventDto.initialize(this, serialNo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, serialNo) { 
        obj['serialNo'] = serialNo;
    }

    /**
     * Constructs a <code>AddRentalItemEventDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/AddRentalItemEventDto} obj Optional instance to populate.
     * @return {module:dto/AddRentalItemEventDto} The populated <code>AddRentalItemEventDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddRentalItemEventDto();

            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('serialNo')) {
                obj['serialNo'] = ApiClient.convertToType(data['serialNo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} itemName
 */
AddRentalItemEventDto.prototype['itemName'] = undefined;

/**
 * @member {String} serialNo
 */
AddRentalItemEventDto.prototype['serialNo'] = undefined;






export default AddRentalItemEventDto;

