/**
 * レンタル予約システムの公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginDto model module.
 * @module dto/LoginDto
 * @version 1.0.0-SNAPSHOT
 */
class LoginDto {
    /**
     * Constructs a new <code>LoginDto</code>.
     * ログインDTO
     * @alias module:dto/LoginDto
     * @param loginId {String} 
     * @param password {String} 
     */
    constructor(loginId, password) { 
        
        LoginDto.initialize(this, loginId, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, loginId, password) { 
        obj['loginId'] = loginId;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/LoginDto} obj Optional instance to populate.
     * @return {module:dto/LoginDto} The populated <code>LoginDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginDto();

            if (data.hasOwnProperty('loginId')) {
                obj['loginId'] = ApiClient.convertToType(data['loginId'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} loginId
 */
LoginDto.prototype['loginId'] = undefined;

/**
 * @member {String} password
 */
LoginDto.prototype['password'] = undefined;






export default LoginDto;

