/**
 * レンタル予約システムの公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RentalItemResourceDto model module.
 * @module dto/RentalItemResourceDto
 * @version 1.0.0
 */
class RentalItemResourceDto {
    /**
     * Constructs a new <code>RentalItemResourceDto</code>.
     * レンタル品DTO
     * @alias module:dto/RentalItemResourceDto
     * @param id {Number} 
     * @param serialNo {String} 
     */
    constructor(id, serialNo) { 
        
        RentalItemResourceDto.initialize(this, id, serialNo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, serialNo) { 
        obj['id'] = id;
        obj['serialNo'] = serialNo;
    }

    /**
     * Constructs a <code>RentalItemResourceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/RentalItemResourceDto} obj Optional instance to populate.
     * @return {module:dto/RentalItemResourceDto} The populated <code>RentalItemResourceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RentalItemResourceDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('serialNo')) {
                obj['serialNo'] = ApiClient.convertToType(data['serialNo'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RentalItemResourceDto.prototype['id'] = undefined;

/**
 * @member {String} itemName
 */
RentalItemResourceDto.prototype['itemName'] = undefined;

/**
 * @member {String} serialNo
 */
RentalItemResourceDto.prototype['serialNo'] = undefined;






export default RentalItemResourceDto;

