/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RentalItemResourceDto from './RentalItemResourceDto';
import UserAccountResourceDto from './UserAccountResourceDto';

/**
 * The ReservationResourceDto model module.
 * @module dto/ReservationResourceDto
 * @version 2.0.0
 */
class ReservationResourceDto {
    /**
     * Constructs a new <code>ReservationResourceDto</code>.
     * 予約DTO
     * @alias module:dto/ReservationResourceDto
     * @param endDateTime {String} 日時型フォーマット
     * @param id {Number} 
     * @param rentalItemId {Number} 
     * @param startDateTime {String} 日時型フォーマット
     * @param userAccountId {Number} 
     */
    constructor(endDateTime, id, rentalItemId, startDateTime, userAccountId) { 
        
        ReservationResourceDto.initialize(this, endDateTime, id, rentalItemId, startDateTime, userAccountId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, endDateTime, id, rentalItemId, startDateTime, userAccountId) { 
        obj['endDateTime'] = endDateTime;
        obj['id'] = id;
        obj['rentalItemId'] = rentalItemId;
        obj['startDateTime'] = startDateTime;
        obj['userAccountId'] = userAccountId;
    }

    /**
     * Constructs a <code>ReservationResourceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/ReservationResourceDto} obj Optional instance to populate.
     * @return {module:dto/ReservationResourceDto} The populated <code>ReservationResourceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReservationResourceDto();

            if (data.hasOwnProperty('endDateTime')) {
                obj['endDateTime'] = ApiClient.convertToType(data['endDateTime'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('rentalItemDto')) {
                obj['rentalItemDto'] = RentalItemResourceDto.constructFromObject(data['rentalItemDto']);
            }
            if (data.hasOwnProperty('rentalItemId')) {
                obj['rentalItemId'] = ApiClient.convertToType(data['rentalItemId'], 'Number');
            }
            if (data.hasOwnProperty('startDateTime')) {
                obj['startDateTime'] = ApiClient.convertToType(data['startDateTime'], 'String');
            }
            if (data.hasOwnProperty('userAccountDto')) {
                obj['userAccountDto'] = UserAccountResourceDto.constructFromObject(data['userAccountDto']);
            }
            if (data.hasOwnProperty('userAccountId')) {
                obj['userAccountId'] = ApiClient.convertToType(data['userAccountId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * 日時型フォーマット
 * @member {String} endDateTime
 */
ReservationResourceDto.prototype['endDateTime'] = undefined;

/**
 * @member {Number} id
 */
ReservationResourceDto.prototype['id'] = undefined;

/**
 * @member {String} note
 */
ReservationResourceDto.prototype['note'] = undefined;

/**
 * @member {module:dto/RentalItemResourceDto} rentalItemDto
 */
ReservationResourceDto.prototype['rentalItemDto'] = undefined;

/**
 * @member {Number} rentalItemId
 */
ReservationResourceDto.prototype['rentalItemId'] = undefined;

/**
 * 日時型フォーマット
 * @member {String} startDateTime
 */
ReservationResourceDto.prototype['startDateTime'] = undefined;

/**
 * @member {module:dto/UserAccountResourceDto} userAccountDto
 */
ReservationResourceDto.prototype['userAccountDto'] = undefined;

/**
 * @member {Number} userAccountId
 */
ReservationResourceDto.prototype['userAccountId'] = undefined;






export default ReservationResourceDto;

