/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationErrorItemImpl from './ValidationErrorItemImpl';

/**
 * The ValidationErrorInfoImpl model module.
 * @module dto/ValidationErrorInfoImpl
 * @version 2.0.0
 */
class ValidationErrorInfoImpl {
    /**
     * Constructs a new <code>ValidationErrorInfoImpl</code>.
     * パラメータチェックエラー情報
     * @alias module:dto/ValidationErrorInfoImpl
     */
    constructor() { 
        
        ValidationErrorInfoImpl.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationErrorInfoImpl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/ValidationErrorInfoImpl} obj Optional instance to populate.
     * @return {module:dto/ValidationErrorInfoImpl} The populated <code>ValidationErrorInfoImpl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationErrorInfoImpl();

            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('errorReason')) {
                obj['errorReason'] = ApiClient.convertToType(data['errorReason'], 'String');
            }
            if (data.hasOwnProperty('errorItems')) {
                obj['errorItems'] = ApiClient.convertToType(data['errorItems'], [ValidationErrorItemImpl]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} errorMessage
 */
ValidationErrorInfoImpl.prototype['errorMessage'] = undefined;

/**
 * @member {String} errorReason
 */
ValidationErrorInfoImpl.prototype['errorReason'] = undefined;

/**
 * @member {Array.<module:dto/ValidationErrorItemImpl>} errorItems
 */
ValidationErrorInfoImpl.prototype['errorItems'] = undefined;






export default ValidationErrorInfoImpl;

