/**
 * レンタル予約システムの公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationErrorItem model module.
 * @module dto/ValidationErrorItem
 * @version 0.0.1-SNAPSHOT
 */
class ValidationErrorItem {
    /**
     * Constructs a new <code>ValidationErrorItem</code>.
     * 1件ごとのチェックエラー情報
     * @alias module:dto/ValidationErrorItem
     */
    constructor() { 
        
        ValidationErrorItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationErrorItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dto/ValidationErrorItem} obj Optional instance to populate.
     * @return {module:dto/ValidationErrorItem} The populated <code>ValidationErrorItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationErrorItem();

            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * エラーとなった項目
 * @member {String} fieldName
 */
ValidationErrorItem.prototype['fieldName'] = undefined;

/**
 * エラーメッセージ
 * @member {String} message
 */
ValidationErrorItem.prototype['message'] = undefined;






export default ValidationErrorItem;

