/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddRentalItemEventDto from './dto/AddRentalItemEventDto';
import AddReservationEventDto from './dto/AddReservationEventDto';
import AddUserAccountEventDto from './dto/AddUserAccountEventDto';
import GenericErrorInfo from './dto/GenericErrorInfo';
import LoginEventDto from './dto/LoginEventDto';
import RentalItemResourceDto from './dto/RentalItemResourceDto';
import ReservationResourceDto from './dto/ReservationResourceDto';
import UserAccountResourceDto from './dto/UserAccountResourceDto';
import UserType from './dto/UserType';
import ValidationErrorInfoImpl from './dto/ValidationErrorInfoImpl';
import ValidationErrorItemImpl from './dto/ValidationErrorItemImpl';
import AdminApi from './api/AdminApi';
import AuthenticateApi from './api/AuthenticateApi';
import CommonApi from './api/CommonApi';
import MemberApi from './api/MemberApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var @ExtactIoRmsGeneratedClientJs = require('index'); // See note below*.
* var xxxSvc = new @ExtactIoRmsGeneratedClientJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new @ExtactIoRmsGeneratedClientJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new @ExtactIoRmsGeneratedClientJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new @ExtactIoRmsGeneratedClientJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddRentalItemEventDto model constructor.
     * @property {module:dto/AddRentalItemEventDto}
     */
    AddRentalItemEventDto,

    /**
     * The AddReservationEventDto model constructor.
     * @property {module:dto/AddReservationEventDto}
     */
    AddReservationEventDto,

    /**
     * The AddUserAccountEventDto model constructor.
     * @property {module:dto/AddUserAccountEventDto}
     */
    AddUserAccountEventDto,

    /**
     * The GenericErrorInfo model constructor.
     * @property {module:dto/GenericErrorInfo}
     */
    GenericErrorInfo,

    /**
     * The LoginEventDto model constructor.
     * @property {module:dto/LoginEventDto}
     */
    LoginEventDto,

    /**
     * The RentalItemResourceDto model constructor.
     * @property {module:dto/RentalItemResourceDto}
     */
    RentalItemResourceDto,

    /**
     * The ReservationResourceDto model constructor.
     * @property {module:dto/ReservationResourceDto}
     */
    ReservationResourceDto,

    /**
     * The UserAccountResourceDto model constructor.
     * @property {module:dto/UserAccountResourceDto}
     */
    UserAccountResourceDto,

    /**
     * The UserType model constructor.
     * @property {module:dto/UserType}
     */
    UserType,

    /**
     * The ValidationErrorInfoImpl model constructor.
     * @property {module:dto/ValidationErrorInfoImpl}
     */
    ValidationErrorInfoImpl,

    /**
     * The ValidationErrorItemImpl model constructor.
     * @property {module:dto/ValidationErrorItemImpl}
     */
    ValidationErrorItemImpl,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The AuthenticateApi service constructor.
    * @property {module:api/AuthenticateApi}
    */
    AuthenticateApi,

    /**
    * The CommonApi service constructor.
    * @property {module:api/CommonApi}
    */
    CommonApi,

    /**
    * The MemberApi service constructor.
    * @property {module:api/MemberApi}
    */
    MemberApi
};
