/**
 * レンタル予約システムの公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddRentalItemDto from './dto/AddRentalItemDto';
import AddReservationDto from './dto/AddReservationDto';
import AddUserAccountDto from './dto/AddUserAccountDto';
import GenericErrorInfo from './dto/GenericErrorInfo';
import LoginDto from './dto/LoginDto';
import RentalItemResourceDto from './dto/RentalItemResourceDto';
import ReservationResourceDto from './dto/ReservationResourceDto';
import UserAccountResourceDto from './dto/UserAccountResourceDto';
import UserType from './dto/UserType';
import ValidationErrorInfo from './dto/ValidationErrorInfo';
import ValidationErrorItem from './dto/ValidationErrorItem';
import AdminApi from './api/AdminApi';
import AuthenticateApi from './api/AuthenticateApi';
import CommonApi from './api/CommonApi';
import MemberApi from './api/MemberApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RmsGeneratedClientJs = require('index'); // See note below*.
* var xxxSvc = new RmsGeneratedClientJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RmsGeneratedClientJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RmsGeneratedClientJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RmsGeneratedClientJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0-SNAPSHOT
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddRentalItemDto model constructor.
     * @property {module:dto/AddRentalItemDto}
     */
    AddRentalItemDto,

    /**
     * The AddReservationDto model constructor.
     * @property {module:dto/AddReservationDto}
     */
    AddReservationDto,

    /**
     * The AddUserAccountDto model constructor.
     * @property {module:dto/AddUserAccountDto}
     */
    AddUserAccountDto,

    /**
     * The GenericErrorInfo model constructor.
     * @property {module:dto/GenericErrorInfo}
     */
    GenericErrorInfo,

    /**
     * The LoginDto model constructor.
     * @property {module:dto/LoginDto}
     */
    LoginDto,

    /**
     * The RentalItemResourceDto model constructor.
     * @property {module:dto/RentalItemResourceDto}
     */
    RentalItemResourceDto,

    /**
     * The ReservationResourceDto model constructor.
     * @property {module:dto/ReservationResourceDto}
     */
    ReservationResourceDto,

    /**
     * The UserAccountResourceDto model constructor.
     * @property {module:dto/UserAccountResourceDto}
     */
    UserAccountResourceDto,

    /**
     * The UserType model constructor.
     * @property {module:dto/UserType}
     */
    UserType,

    /**
     * The ValidationErrorInfo model constructor.
     * @property {module:dto/ValidationErrorInfo}
     */
    ValidationErrorInfo,

    /**
     * The ValidationErrorItem model constructor.
     * @property {module:dto/ValidationErrorItem}
     */
    ValidationErrorItem,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The AuthenticateApi service constructor.
    * @property {module:api/AuthenticateApi}
    */
    AuthenticateApi,

    /**
    * The CommonApi service constructor.
    * @property {module:api/CommonApi}
    */
    CommonApi,

    /**
    * The MemberApi service constructor.
    * @property {module:api/MemberApi}
    */
    MemberApi
};
