/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ExtactIoRmsGeneratedClientJs);
  }
}(this, function(expect, @ExtactIoRmsGeneratedClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ExtactIoRmsGeneratedClientJs.AdminApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminApi', function() {
    describe('addRentalItem', function() {
      it('should call addRentalItem successfully', function(done) {
        //uncomment below and update the code to test addRentalItem
        //instance.addRentalItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUserAccount', function() {
      it('should call addUserAccount successfully', function(done) {
        //uncomment below and update the code to test addUserAccount
        //instance.addUserAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRentalItem', function() {
      it('should call deleteRentalItem successfully', function(done) {
        //uncomment below and update the code to test deleteRentalItem
        //instance.deleteRentalItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReservation', function() {
      it('should call deleteReservation successfully', function(done) {
        //uncomment below and update the code to test deleteReservation
        //instance.deleteReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserAccount', function() {
      it('should call deleteUserAccount successfully', function(done) {
        //uncomment below and update the code to test deleteUserAccount
        //instance.deleteUserAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllRentalItems', function() {
      it('should call getAllRentalItems successfully', function(done) {
        //uncomment below and update the code to test getAllRentalItems
        //instance.getAllRentalItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllReservations', function() {
      it('should call getAllReservations successfully', function(done) {
        //uncomment below and update the code to test getAllReservations
        //instance.getAllReservations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUserAccounts', function() {
      it('should call getAllUserAccounts successfully', function(done) {
        //uncomment below and update the code to test getAllUserAccounts
        //instance.getAllUserAccounts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRentalItem', function() {
      it('should call updateRentalItem successfully', function(done) {
        //uncomment below and update the code to test updateRentalItem
        //instance.updateRentalItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReservation', function() {
      it('should call updateReservation successfully', function(done) {
        //uncomment below and update the code to test updateReservation
        //instance.updateReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserAccount', function() {
      it('should call updateUserAccount successfully', function(done) {
        //uncomment below and update the code to test updateUserAccount
        //instance.updateUserAccount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
