/**
 * レンタル予約システム公開API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: -
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@ExtactIoRmsGeneratedClientJs);
  }
}(this, function(expect, @ExtactIoRmsGeneratedClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @ExtactIoRmsGeneratedClientJs.MemberApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberApi', function() {
    describe('addReservation', function() {
      it('should call addReservation successfully', function(done) {
        //uncomment below and update the code to test addReservation
        //instance.addReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('canRentedItemAtTerm', function() {
      it('should call canRentedItemAtTerm successfully', function(done) {
        //uncomment below and update the code to test canRentedItemAtTerm
        //instance.canRentedItemAtTerm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelReservation', function() {
      it('should call cancelReservation successfully', function(done) {
        //uncomment below and update the code to test cancelReservation
        //instance.cancelReservation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findCanRentedItemAtTerm', function() {
      it('should call findCanRentedItemAtTerm successfully', function(done) {
        //uncomment below and update the code to test findCanRentedItemAtTerm
        //instance.findCanRentedItemAtTerm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findReservationByRentalItemAndStartDate', function() {
      it('should call findReservationByRentalItemAndStartDate successfully', function(done) {
        //uncomment below and update the code to test findReservationByRentalItemAndStartDate
        //instance.findReservationByRentalItemAndStartDate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findReservationByRentalItemId', function() {
      it('should call findReservationByRentalItemId successfully', function(done) {
        //uncomment below and update the code to test findReservationByRentalItemId
        //instance.findReservationByRentalItemId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findReservationByReserverId', function() {
      it('should call findReservationByReserverId successfully', function(done) {
        //uncomment below and update the code to test findReservationByReserverId
        //instance.findReservationByReserverId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllRentalItems', function() {
      it('should call getAllRentalItems successfully', function(done) {
        //uncomment below and update the code to test getAllRentalItems
        //instance.getAllRentalItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOwnReservations', function() {
      it('should call getOwnReservations successfully', function(done) {
        //uncomment below and update the code to test getOwnReservations
        //instance.getOwnReservations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
